### Get emulator status
GET http://localhost:5000/status

### endpoint for emulator state changes
POST http://localhost:5000/dev/mode
Content-Type: application/json

{
    "mode": "REAL"
}

### endpoint for emulator state changes
POST http://localhost:5000/dev/mode
Content-Type: application/json

{
    "mode": "SIMULATED"
}

### endpoint for emulator state changes
POST http://localhost:5000/dev/state
Content-Type: application/json

{
    "running": true,
    "demo": "asdf"
}

### endpoint for emulator state changes
POST http://localhost:5000/dev/state
Content-Type: application/json

{
    "running": false,
    "demo": "asdf"
}

### endpoint for emulator error simulation
POST http://localhost:5000/dev/error
Content-Type: application/json

{
    "code": "EMULATOR_CRASHED",
    "message": "Pooooop!"
}