### Get emulator status
GET http://localhost:5000/status

### Toggle emulator state
POST http://localhost:5000/dev/toggle

### endpoint for emulator state changes
POST http://localhost:5000/dev/mode
Content-Type: application/json

{
    "mode": "SIMULATED"
}

### endpoint for emulator state changes
POST http://localhost:5000/dev/state
Content-Type: application/json

{
    "running": "true",
    "demo": "12"
}